### ISSUE TITLE
ModernKiosk mode when computer boots/restarts

### ISSUE THREAD

**Issue by ajd2010** [racketlogger/ModernKiosk#8]
Hello,
I think your extension is awesome and by far the the better of the Kiosk modes I have found, I would like to know if there is a way to make it so that Firefox in Modern Kiosk mode can start up automatically when booting up the PC or restarting the PC?

**Comment by cpg** [comment]
Thanks for your kind words. However, this is really dependent on the OS the browser is running on.

It's tangentially related to #6, however, it's outside of the realm of an extension itself, so we'll close this, since the extension cannot do a lot for this specifically, I believe.

That said, it would be *really really good* to develop resources (tips, docs, etc.) for everyone using this extension to run the browser as the sole main app in the OS, regardless of rebooting, etc.
